apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "final-app.fullname" . }}
  labels: {{- include "final-app.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  {{- if .Values.persistence.enabled }}
  DATA_DIR: {{ .Values.persistence.mountPath | quote }}
  {{- end }}
