{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "final-app.fullname" . }}
  labels: {{- include "final-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_TOKEN: {{ required "secret.apiToken is required" .Values.secret.apiToken | quote }}
{{- end }}
