apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  labels: {app: gitops-demo}
spec:
  replicas: 3
  selector:
    matchLabels: {app: gitops-demo}
  template:
    metadata:
      labels: {app: gitops-demo}
    spec:
      containers:
        - name: app
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet: {path: /, port: 80}
          resources:
            requests: {cpu: 10m, memory: 16Mi}
            limits: {cpu: 100m, memory: 64Mi}
